name: portainer
services:
    portainer-ee:
        ports:
            - 9443:9443
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        image: portainer/portainer-ee:latest
volumes:
    portainer_data:
        external: true
        name: portainer_data